name:                salary-graph
version:             0.1.0
homepage:            https://github.com/matsubara0507/salary-graph#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          nobutada0507@gmail.com
copyright:           2021 MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/salary-graph#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- GHC2021

dependencies:
- base >= 4.7 && < 5
- aeson
- elm-bridge
- servant-elm
- servant-server
- warp

library:
  source-dirs: src

executables:
  salary-graph:
    main: Main.hs
    source-dirs: app
    dependencies:
    - salary-graph
