name: Build Application

on:
  pull_request: null
  push:
    branches:
    - main

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Cache Bazel
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}

    - name: Build binary
      run: |
        bazelisk build //:salary-graph
        bazel-bin/salary-graph --version
        bazel-bin/salary-graph --help
    - name: Build image
      run: |
        bazelisk run //:image
        docker run --rm bazel:image -- --version

    # Build and Push Docker Image
    - name: Setup QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: matsubara0507
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      if: ${{ github.event_name != 'pull_request' }}
      run: bazelisk run //:push
